// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user, ensure the account is not locked.
	// (POST /api/authz/auth/{username})
	AuthzAuthUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Lookup user POSIX attributes
	// (GET /api/authz/lookup/{username})
	AuthzLookupUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Compute a crypt(3) plaintext hash
	// (POST /api/crypto/hash)
	ComputeHash(w http.ResponseWriter, r *http.Request)
	// Verify a plaintext against a stored hash
	// (POST /api/crypto/verify)
	VerifyHash(w http.ResponseWriter, r *http.Request)

	// (GET /api/groups)
	ListGroups(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/groups/{groupname})
	DeleteGroup(w http.ResponseWriter, r *http.Request, groupname GroupnameParam)

	// (GET /api/groups/{groupname})
	GetGroup(w http.ResponseWriter, r *http.Request, groupname GroupnameParam)
	// Create-or-ensure group (idempotent)
	// (PUT /api/groups/{groupname})
	EnsureGroup(w http.ResponseWriter, r *http.Request, groupname GroupnameParam)
	// Set or change group description
	// (PUT /api/groups/{groupname}/description)
	SetGroupDescription(w http.ResponseWriter, r *http.Request, groupname GroupnameParam)
	// Health check
	// (GET /api/health)
	Health(w http.ResponseWriter, r *http.Request)
	// Random secret generator
	// (GET /api/secret)
	GenerateSecret(w http.ResponseWriter, r *http.Request, params GenerateSecretParams)
	// List users (without passwords)
	// (GET /api/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Delete user
	// (DELETE /api/users/{username})
	DeleteUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Get user details (without password)
	// (GET /api/users/{username})
	GetUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Create-or-ensure user (idempotent)
	// (PUT /api/users/{username})
	EnsureUser(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Set or change user description
	// (PUT /api/users/{username}/description)
	SetUserDescription(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// List user top-level directories
	// (GET /api/users/{username}/directories)
	ListUserDirs(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Delete user top-level directory if doesn't contain any files
	// (DELETE /api/users/{username}/directories/{dirname})
	DeleteUserDir(w http.ResponseWriter, r *http.Request, username UsernameParam, dirname DirnameParam)
	// Create-or-ensure user directory (idempotent)
	// (PUT /api/users/{username}/directories/{dirname})
	EnsureUserDir(w http.ResponseWriter, r *http.Request, username UsernameParam, dirname DirnameParam)
	// Set or change user disabled status
	// (PUT /api/users/{username}/disabled)
	SetUserDisabled(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Set or change user expiration
	// (PUT /api/users/{username}/expiration)
	SetUserExpiration(w http.ResponseWriter, r *http.Request, username UsernameParam)
	// Set or change user password
	// (PUT /api/users/{username}/password)
	SetUserPassword(w http.ResponseWriter, r *http.Request, username UsernameParam)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Authenticate user, ensure the account is not locked.
// (POST /api/authz/auth/{username})
func (_ Unimplemented) AuthzAuthUser(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lookup user POSIX attributes
// (GET /api/authz/lookup/{username})
func (_ Unimplemented) AuthzLookupUser(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Compute a crypt(3) plaintext hash
// (POST /api/crypto/hash)
func (_ Unimplemented) ComputeHash(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify a plaintext against a stored hash
// (POST /api/crypto/verify)
func (_ Unimplemented) VerifyHash(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/groups)
func (_ Unimplemented) ListGroups(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/groups/{groupname})
func (_ Unimplemented) DeleteGroup(w http.ResponseWriter, r *http.Request, groupname GroupnameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/groups/{groupname})
func (_ Unimplemented) GetGroup(w http.ResponseWriter, r *http.Request, groupname GroupnameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create-or-ensure group (idempotent)
// (PUT /api/groups/{groupname})
func (_ Unimplemented) EnsureGroup(w http.ResponseWriter, r *http.Request, groupname GroupnameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set or change group description
// (PUT /api/groups/{groupname}/description)
func (_ Unimplemented) SetGroupDescription(w http.ResponseWriter, r *http.Request, groupname GroupnameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /api/health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Random secret generator
// (GET /api/secret)
func (_ Unimplemented) GenerateSecret(w http.ResponseWriter, r *http.Request, params GenerateSecretParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users (without passwords)
// (GET /api/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete user
// (DELETE /api/users/{username})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user details (without password)
// (GET /api/users/{username})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create-or-ensure user (idempotent)
// (PUT /api/users/{username})
func (_ Unimplemented) EnsureUser(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set or change user description
// (PUT /api/users/{username}/description)
func (_ Unimplemented) SetUserDescription(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List user top-level directories
// (GET /api/users/{username}/directories)
func (_ Unimplemented) ListUserDirs(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete user top-level directory if doesn't contain any files
// (DELETE /api/users/{username}/directories/{dirname})
func (_ Unimplemented) DeleteUserDir(w http.ResponseWriter, r *http.Request, username UsernameParam, dirname DirnameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create-or-ensure user directory (idempotent)
// (PUT /api/users/{username}/directories/{dirname})
func (_ Unimplemented) EnsureUserDir(w http.ResponseWriter, r *http.Request, username UsernameParam, dirname DirnameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set or change user disabled status
// (PUT /api/users/{username}/disabled)
func (_ Unimplemented) SetUserDisabled(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set or change user expiration
// (PUT /api/users/{username}/expiration)
func (_ Unimplemented) SetUserExpiration(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set or change user password
// (PUT /api/users/{username}/password)
func (_ Unimplemented) SetUserPassword(w http.ResponseWriter, r *http.Request, username UsernameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthzAuthUser operation middleware
func (siw *ServerInterfaceWrapper) AuthzAuthUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthzAuthUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthzLookupUser operation middleware
func (siw *ServerInterfaceWrapper) AuthzLookupUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthzLookupUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ComputeHash operation middleware
func (siw *ServerInterfaceWrapper) ComputeHash(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ComputeHash(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyHash operation middleware
func (siw *ServerInterfaceWrapper) VerifyHash(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyHash(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupname" -------------
	var groupname GroupnameParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupname", chi.URLParam(r, "groupname"), &groupname, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupname", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, groupname)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupname" -------------
	var groupname GroupnameParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupname", chi.URLParam(r, "groupname"), &groupname, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupname", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, groupname)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnsureGroup operation middleware
func (siw *ServerInterfaceWrapper) EnsureGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupname" -------------
	var groupname GroupnameParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupname", chi.URLParam(r, "groupname"), &groupname, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupname", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnsureGroup(w, r, groupname)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetGroupDescription operation middleware
func (siw *ServerInterfaceWrapper) SetGroupDescription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupname" -------------
	var groupname GroupnameParam

	err = runtime.BindStyledParameterWithOptions("simple", "groupname", chi.URLParam(r, "groupname"), &groupname, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupname", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetGroupDescription(w, r, groupname)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateSecret operation middleware
func (siw *ServerInterfaceWrapper) GenerateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GenerateSecretParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameter("form", true, false, "size", r.URL.Query(), &params.Size)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateSecret(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnsureUser operation middleware
func (siw *ServerInterfaceWrapper) EnsureUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnsureUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetUserDescription operation middleware
func (siw *ServerInterfaceWrapper) SetUserDescription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetUserDescription(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserDirs operation middleware
func (siw *ServerInterfaceWrapper) ListUserDirs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserDirs(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserDir operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserDir(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// ------------- Path parameter "dirname" -------------
	var dirname DirnameParam

	err = runtime.BindStyledParameterWithOptions("simple", "dirname", chi.URLParam(r, "dirname"), &dirname, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dirname", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserDir(w, r, username, dirname)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnsureUserDir operation middleware
func (siw *ServerInterfaceWrapper) EnsureUserDir(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// ------------- Path parameter "dirname" -------------
	var dirname DirnameParam

	err = runtime.BindStyledParameterWithOptions("simple", "dirname", chi.URLParam(r, "dirname"), &dirname, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dirname", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnsureUserDir(w, r, username, dirname)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetUserDisabled operation middleware
func (siw *ServerInterfaceWrapper) SetUserDisabled(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetUserDisabled(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetUserExpiration operation middleware
func (siw *ServerInterfaceWrapper) SetUserExpiration(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetUserExpiration(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) SetUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username UsernameParam

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	ctx = context.WithValue(ctx, XApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, XContentSha256Scopes, []string{})

	ctx = context.WithValue(ctx, XTimestampScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetUserPassword(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/authz/auth/{username}", wrapper.AuthzAuthUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/authz/lookup/{username}", wrapper.AuthzLookupUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/crypto/hash", wrapper.ComputeHash)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/crypto/verify", wrapper.VerifyHash)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/groups/{groupname}", wrapper.DeleteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/groups/{groupname}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/groups/{groupname}", wrapper.EnsureGroup)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/groups/{groupname}/description", wrapper.SetGroupDescription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/secret", wrapper.GenerateSecret)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/users/{username}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{username}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{username}", wrapper.EnsureUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{username}/description", wrapper.SetUserDescription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users/{username}/directories", wrapper.ListUserDirs)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/users/{username}/directories/{dirname}", wrapper.DeleteUserDir)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{username}/directories/{dirname}", wrapper.EnsureUserDir)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{username}/disabled", wrapper.SetUserDisabled)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{username}/expiration", wrapper.SetUserExpiration)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/users/{username}/password", wrapper.SetUserPassword)
	})

	return r
}
