// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w87XLbuHavgmE9s3JKfVix3Rt38sOJd7Oem00y8SZ3p7EbweSRhBsK4AKgbSXjmT5E",
	"n7BP0jkASEIUKCu25aTb+IdMEV8H5/scHOhLlIhZLjhwraKDL9EUaArSPL4UCdVM8F/NK3yTgkoky/Fl",
	"dBC9e/uSiDHRUyCJBKohJRKUKGQCURypZAoziqPGQs6ojg6iQrIojvQ8h+ggUloyPomur6/jKKeSzkC7",
	"dY+Y5HQGb/Dl8qpv3RKEpcA1GzOQpJPaIds9cpJRNSVcaEKzTFxC2oviiOHAnOppFEfYLzqI3IgojiT8",
	"WTAJaXSgZQE+4FsSxtFB9C/9GkV926r6DsgIwX8hRZGvANm0e/CuD+WknPnWcFawGUjfKfhq3BZuzFcg",
	"txxya6hLOC17SFC54AoMdzyj6Vv4swCl8VsiuAZuHmmeZ8xybP+fCvfzZc3VfpZSSLvUIj6eUWRpu9h1",
	"HD0XfJyx5AEWLlci//Nf/10JFYErprQil0xPScrGY5DANUmppgY6K4PLVC0b4pBwt4HouvYbSsDAegQZ",
	"BFcqG67j6Bchz1maAl/udcxVMR6zhCH0OcgZU4oJrnDYMddI+ewE5AVIi5+NY7tclCizKgHbMY5eief1",
	"wotjXglSAmU66l9EwdPNw/pKaDI2S6E4c1roqZDsc4gavyFe+aTP+AXNWEqwL4q1IzyOz9Mwy5QN98Qy",
	"16Xcm3mei1leaPiVqqmT5GcinRt8pSnDkTR7I0UOUjOU+THNFMRR7r36EtFsIiTT09lNmMRlDqvOaGwy",
	"yriGqwBR35RNRAsyRV3XcSzBAT+VFhIUqWbYRv03Y/wl8ImeRgc7TesWR5eSaXjNs7lVgKjNkHoqIBYa",
	"pMEbSUTBdY+8daqzXyhIyVhIksh5rknH/OuqKR3u7ferL3s7w+3eKT+ecCH9/t1Zuhe7R5rLHUJ5SiS9",
	"JBUKVa93yt8bHpGUT8CMZYrskMFg0OuZf+bxlON+6RWbFbPoYGdg/gwG6jcVChBFEzBypGimX4ZUwQnN",
	"NMkM9rwNYncyAe7wsbDmvr/c8lrXvsX54HGJT/ezapw4/yckTrd7TGnNzYNyJXLbMn5+KbLMMGJMoDfp",
	"kdNoa3/LMtDTvcFgsHVaDAaPE0SYeQL3ImUTUO7VaRRwutrRZAAJYejIh+xLTZLh3l4c8SLL6HkGpZlv",
	"rBeXTl3AZjAJiRZyTrC99DE6/W3kwIarUbPB8G8eHwzRg9Sow6OD6D8/HHb/g3Y/D7pPeh+7Z/+6FQWg",
	"+ZmrQoLxjW6vgtJFhKz0Fr2u13E0YemNftvxkWELYXG2qutbyKhmF/AGfbAmaXGpEDUtBtDP+hYISJlC",
	"bnGWZ0yLTFdrOFDPhciAmt5wlTNZmZ4qnEAT1dXMuJk38l/tSa/vMN8G/ciKSl0Kma4yL0KSMUOPwxiZ",
	"FHLgKeMTIjgZleM/MvURm0dO7dZm5m/rmJnmNMvg/GMKnBh01YuOUOq0i+aoItSD89+J0FOQl0wBYZpc",
	"siwj52CaIHW+U1exFCzADTouw9jkVC/WqXAY2EeQm0tH8Su4NxGpoS1c0VmOnBO9O/n57cfnr1/98vL4",
	"+e8htTEDpejEjFqtUM3cdf8QyCjgC8Ex4/rx0Fdyu8Mnu0/2/234ZM/XdS0m9oU1l3ACiQR9BxN2ThXs",
	"7xYyC1hrMzcBjttLSYHeJXn39mVX0TGQZ2ZgL4S3KVzdOBtVBPW8TKgCMoUrmkLCZjQLTqjYZ/h4PtcB",
	"PRS9KmbnIIkYE9OBGO9Ji9KhAJOwUGZxb+42D8Jbye4j9jAUpCuy8TEfi+/QmjyUElwh2f42LehugThK",
	"pjORdlUOSTtiwz6ETbA8oP+w6L4twYPNtXvtZ36iOAKOa36IKucct15559UX6977X/d2UD1IeukG4ZOa",
	"0p360Q5wX7D7WQh2oJmenmiqC3UnPcF5KCv4OrcTGIPAEiC2I5q8C5AY6BMLC+nkEhRwTS7REE0NWPPt",
	"FgViGgOrXYCk6CObDkSZXUUhJ0ICdRF4M+eF7030cQ4IVsHdaqQjeDYnChyEdvKnP1UdfjLA3uh6KE2l",
	"hvQjDUScv7MZKE1nuV3CqiaLNzcMlwi6PEvrFDm2fFSQhJStndT2IYyjBhQ8VQvTM673d2/WiY70NVkW",
	"9rgASEiQF3RFgB62leTUENSwip5STWaF0kaizWI2DUaJsvI+6o+2TWRb9UoE1xQ3mtMEVI8cWj1AkimV",
	"NNEg1QHJAMVexSRlE6bxv9CkM+qNtmNS8BSkSoQE0hl9xDfTeY5E6oy6+A0X8xbvEVKGx1U6YDDcbeYH",
	"WhWN/63fPXsU1DsnoD3l//Cee4MR/GlClD4BjRHGkfP27wCvFy80RbsJU9l1BUA/VwHF7UG6e1DSANyb",
	"cAXob5w7fHvA2+MTnJ+UzYTxvNA9cjxeDkmemolHcaWvQNpwwIQzTDvXEFtddFdbw5YZEUNuwguaFWDl",
	"mGYSaDrHMMOPRL6XiMiC2iNmnEV2GCX4csIugNe5wxrR5zBGJaO0MLqO6dvFT18bM7273wAEmedB3d5V",
	"OuGecgbfnWMdR8XNML2zMFWHcOuftS0ylHeKVxg/veG7e179gh+/UgO/86Ba1j4P6MK/B8nG87sdQoS1",
	"yEmR50JqdUBOo62drdMoxgd07svnvfJhf+s06p3y0mfO5iYxP4UrYjO4inQeD5/+drQXk93B05NfD7s7",
	"MdnfNU/Dvf2Y7Az/Zr645P9vR3t904tQ1CgWEBdcw4Qmc+O1YBuiVUIiZjPgKaQLKqdG0lpnJQnlKUtN",
	"ZC3Qx2fjOaETyrjSVhtqcyBhFPdXn5c0eNJg/KZcvk/aW8c3KWhIjEvbHucduT5WydcBH7Ix6cyoMVyn",
	"UcE/cXHJTyMTZXDBuxgDEquUVDjigTKj1RJdpYxOuFCaJcRlmWwEYfDvjvjImLJMYeSFZLDLoUgVvOKM",
	"tQIYO2fonPAfU9BTsPPXlm1GdTIFZd6WVL/Ba6uWiEOIXyYyhlWQFJLp+QnqMUuzQ3caWun9xmmKkOTX",
	"3w6fN05CD0ihgIwWBh/YjvY0ZQpXXcUmnOpCgj1UGRFCcLpnQCXItSZ0Xe2UNGddm4Ny8xn5M6UU9hi1",
	"LqagC5uqMEFz9neYI3n+OLSPS/s9fHNMPsHcr+Yok2EKMkiseBpqoeNR58SCcFx1EehPMA/C4A7KT2wS",
	"Yn3UGzfvHMjIpi+e1hj3z7AQ3R0E1ik+K3Cu+MhVaJBzkc4xDCOvZwy3xhSxe7CSYX3SIMF67di/6rrz",
	"/Dq/srz5Koq/zcZ1OdjtveDsqlu99PZf0i6XcAEc1Xee0TmhWtPkk9rAzisgljeNAsict9dguhSNstLS",
	"RvHIg6j1ZpTTCYIxZhmoudIwIzRJQCmC0KDWJapIpmiq0PFQxlIZH0P1LGLOpUUGRvJGi+bFecYSAjzN",
	"BeNaEadRGnt0+wdWqapHj5Akjx6hanz0yCLm0SNiPCIgnYXzGFPeJviYTQrrT243wfndzNicxcHitKAt",
	"jSCjP7qHOev+HeYjs79FHTEKz+xgXXPeuDlpjK0Vh45s4mL0R9dJbNeKrDtl0kybo5Cx6lrqoNBHxgQo",
	"S9+d3gB5XuTAsekgetwb9B6boENPjRbu05z1kQSfzWf/S+lIXpvwU9jKLbS1BsDjFLkGu+MHeoHRYkXg",
	"h7D/WnfpL5a1XZ9Z2+L5dC01OVfdy8vLLhrGbiEzdxKxWKTTODPKGHD9keULQQXLL3aD3pMXaS83SqFF",
	"IrJgow0g11unLQwMGM3rZj1es7huONgNSHQtTehK8pQANw4+6XDhtC4CvTsYLA9ulNDtDnbCdspi1nr7",
	"/npu5sct2YqGpKPDg3CVJU8l5/VLrDhIh63zJab4Br2kMowxI/ZCe6vqxk4W6saQfsVsRuW8gTwDTkzA",
	"HL0b+fWWw51nIvlkfTJNJ8j5Vi6iM5zTE6tMiE9F3hCsCbTJ1UvT/d4k6yZ+MZVwtm605JTtHjnUWrLz",
	"QoMiF4xWmstjoYVis6vuWHVTJhelcZn1Tb8JJEKt15M15Ht1smMQzIWbmdQUsmytNYu7r3m9KfGyg3ZD",
	"9Y2uzhBtZBXR30USLBcaGSBvXp8c/4Gei2OJFRxvjr9Evwy1S/PRrJc11VuKUFtC1nm8bV3EOhFpPV5U",
	"YFWYZjL4NNO9U96ta+VI11lfF73XjaZ6zmt1IX3dwbqIfheM9EkHZQYSdFBM6db2woi9naE/Yr9lRBQ3",
	"RNurWIvWNXhfV4TaUqi5lh0ZbAYKL5wPFMeac9fE9k89kxSavoK371WU1/y9ekioTNmPSaODD2c+77s9",
	"+OxZh8sup1EKwHPD8MsSYDMr7TLw3obQCn3+OiiX4oKlkLZE535q5pSXiasayM7WzhbpE8vp+LBnPve3",
	"tnvES1qhq5gjszaTVy4ftYMfw719/OcyVUvsXCdtNsTN4YTfAzNzS2oqwMvv/USOBFVk+nvi6Pcuz+cx",
	"Vpnzoz5brWJsG915vssiBl4ypV0EuMQt2PaibLoTtZiGmVorbW9ON67rUFhKGqSc+OSZ4tVYXyjgrx3d",
	"1YPqqxV3JW5JGYfJJmX6X6oc/7UlTwYa2q59WFItUco2vnBtIe9xNezenZIHQunuOmBVNz7unQZxWBpe",
	"gBMGkoKmLFuWiRegW9B8f/rLE4RvzPhfSaUwpr8uGGrc88NoKC9024Ura2EtydiYME1SATbOMxe5QkbQ",
	"q0vfkBVsqXxf3wzeQFd3ceg6jobr8EF5N+12lu3BWO3JGjspLwfe2eLWXqNBTlfIrksZWGbqsBRmuUBe",
	"2I6+Son3G6ft98X+i0x84vTQ0cJx8SaYub0cav1c100K5Hl9y+975tCHNFk1h56AucuQTM21sdI8+WRv",
	"5U5bO9iauLJVqps0Za11sK2Wbc/S5cFXLytCq8LTlZ65nZkkU0g+eQR4Yw5LPALY475W79t66xNJ8ylL",
	"MMrrKi0FnxBJeSpm7rSwrKoXknTKAvvUtamq0CAHqZjSkG4HnBb/3sJyftIcTf1ZgJzXJ1OKfV78hYHq",
	"CtHjYWuFyM5+IK92tklXqf1Gxgrf6fuI7t6GabwqmDOHdq3ijPHaO9PjIcK1qhbtLxWtealUjIztKWnn",
	"kumpKOpyQuX7BBblDSI1zg3qqC4UuLlTgzvGbT/s5iIBXcRcWOQ2qRWHZeiFrQDepE2sBef/VnR3b4TB",
	"KNucULgge1m+toMEu+upWjCOtLGajSMNUFUhT0rO52RUy/Fo4bdBvKIYNMaaamgPNiuW2lSs2bxj/CPU",
	"vE++/25iU8OgLaHpTWbobnFpqzQthaXmMsqPqPT/V1Tq1HkoKL2ZL92PU7jyn5Wu7RF7IO+2+umxv7hz",
	"S7TIuxlcQEZ8OtTkO/Le3t0Ir8ME/S/ud+PW9JyP2A/neZPOc4BF5oSNTaad/1TfAaV8bgtPN8U98Y0D",
	"Fn7VcG2X7ycV3mLDESy58o5+YJBdN+2K/aV5Newm1YRscZgWeXOFZqqvwG3UZyrX2ZjD1HZN+IfH9M08",
	"JkcN7zcV1vWaFu9ebpIx64vcm2XN8IXxH8z5rZgTfLqvzZd+Pf5GEjYnoBXhcFnf7S6zR5ZLylrUXMIF",
	"E4UigkNvyR43bvpvlrNDvyfwg6+/FV97d/iXuHrxuGbpsuOHM+8moPnSuJJn3nk31T6cIR/bmyZWCMyP",
	"fkV9jIX+NwAA//+I7rKjF1wAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
