// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"time"
)

const (
	AuthorizationScopes  = "Authorization.Scopes"
	XApiKeyScopes        = "XApiKey.Scopes"
	XContentSha256Scopes = "XContentSha256.Scopes"
	XTimestampScopes     = "XTimestamp.Scopes"
)

// Defines values for HashAlgorithm.
const (
	CryptApr1   HashAlgorithm = "crypt-apr1"
	CryptMd5    HashAlgorithm = "crypt-md5"
	CryptSha256 HashAlgorithm = "crypt-sha256"
	CryptSha512 HashAlgorithm = "crypt-sha512"
	RawMd5      HashAlgorithm = "raw-md5"
	RawSha1     HashAlgorithm = "raw-sha1"
	RawSha256   HashAlgorithm = "raw-sha256"
	RawSha512   HashAlgorithm = "raw-sha512"
)

// ComputeHashRequestBody defines model for ComputeHashRequestBody.
type ComputeHashRequestBody struct {
	// Algorithm Hash algorithm identifier.
	Algorithm HashAlgorithm `json:"algorithm"`

	// Plaintext Plaintext to hash (server never stores plaintext).
	Plaintext *string `json:"plaintext,omitempty"`

	// Rounds Iteration count. Required/used for crypt (crypt-sha256/crypt-sha512).
	// Ignored for crypt-md5, crypt-apr1 and raw algorithms..
	// Valid range for is 1 000..1 000 000.
	Rounds *int `json:"rounds,omitempty"`

	// SaltLen Salt length for crypt salt generation
	SaltLen *int `json:"saltLen,omitempty"`
}

// ComputeHashResponseBody defines model for ComputeHashResponseBody.
type ComputeHashResponseBody struct {
	// Algorithm Hash algorithm identifier.
	Algorithm HashAlgorithm `json:"algorithm"`

	// Hash Full hash, e.g. "$6$rounds=5000$<salt>$<digest>"
	Hash string `json:"hash"`
}

// Description defines model for Description.
type Description = string

// Dirname Directory name. Slash (/) is not allowed.
type Dirname = string

// EnsureGroupRequestBody defines model for EnsureGroupRequestBody.
type EnsureGroupRequestBody struct {
	Description *Description `json:"description"`
	Gid         GID          `json:"gid"`

	// Home Relative path string that must not start with a slash (`/`) and must not contain spaces. Allowed characters: letters, digits, dot (`.`), underscore (`_`), hyphen (`-`), and slash (`/`).
	Home *RelativePath `json:"home,omitempty"`
}

// EnsureUserRequestBody defines model for EnsureUserRequestBody.
type EnsureUserRequestBody struct {
	Description *Description `json:"description"`
	Disabled    *bool        `json:"disabled,omitempty"`
	Expiration  *time.Time   `json:"expiration"`

	// Groupname Group name. Slash (/) is not allowed.
	Groupname Groupname `json:"groupname"`

	// Home Relative path string that must not start with a slash (`/`) and must not contain spaces. Allowed characters: letters, digits, dot (`.`), underscore (`_`), hyphen (`-`), and slash (`/`).
	Home *RelativePath `json:"home,omitempty"`

	// Password Plaintext or final hash depending on `password_is_hash`.
	Password *string `json:"password,omitempty"`

	// PasswordIsHash When true, `password` is treated as a final hash; otherwise it will be hashed server-side.
	PasswordIsHash *bool `json:"password_is_hash,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GID defines model for GID.
type GID = uint32

// GenerateSecretResponseBody defines model for GenerateSecretResponseBody.
type GenerateSecretResponseBody struct {
	// Base64url Secret encoded using URL-safe Base64.
	Base64url string `json:"base64url"`

	// Hex Secret encoded as lowercase hexadecimal.
	Hex string `json:"hex"`

	// SizeBytes Number of bytes used to generate the secret.
	SizeBytes int `json:"size_bytes"`
}

// GroupInfo defines model for GroupInfo.
type GroupInfo struct {
	Description *Description `json:"description"`
	Gid         GID          `json:"gid"`

	// Groupname Group name. Slash (/) is not allowed.
	Groupname Groupname `json:"groupname"`

	// Home Relative path string that must not start with a slash (`/`) and must not contain spaces. Allowed characters: letters, digits, dot (`.`), underscore (`_`), hyphen (`-`), and slash (`/`).
	Home RelativePath `json:"home"`
}

// Groupname Group name. Slash (/) is not allowed.
type Groupname = string

// HashAlgorithm Hash algorithm identifier.
type HashAlgorithm string

// HealthStatusResponseBody defines model for HealthStatusResponseBody.
type HealthStatusResponseBody struct {
	// Banner Optional service banner or version string (present when healthy).
	Banner string `json:"banner"`

	// Healthy Overall health status
	Healthy bool `json:"healthy"`

	// Reason Reason for being unhealthy (only set when status='unhealthy').
	Reason *string `json:"reason"`

	// StartedAt Timestamp when the service started.
	StartedAt time.Time `json:"started_at"`

	// UptimeSec Service uptime in seconds.
	UptimeSec int64 `json:"uptime_sec"`
}

// RelativePath Relative path string that must not start with a slash (`/`) and must not contain spaces. Allowed characters: letters, digits, dot (`.`), underscore (`_`), hyphen (`-`), and slash (`/`).
type RelativePath = string

// SetDescriptionRequestBody defines model for SetDescriptionRequestBody.
type SetDescriptionRequestBody struct {
	Description *Description `json:"description"`
}

// SetUserDisabledRequestBody defines model for SetUserDisabledRequestBody.
type SetUserDisabledRequestBody struct {
	Disabled bool `json:"disabled"`
}

// SetUserExpirationRequestBody defines model for SetUserExpirationRequestBody.
type SetUserExpirationRequestBody struct {
	Expiration *time.Time `json:"expiration"`
}

// SetUserPasswordRequestBody defines model for SetUserPasswordRequestBody.
type SetUserPasswordRequestBody struct {
	// Password User password input. If `password_is_hash=false`, the server will hash it using the default algorithm. If `password_is_hash=true`, the value must already be a final hash.
	Password *string `json:"password,omitempty"`

	// PasswordIsHash When true, `password` is treated as a final hash value. When false, the server will hash the given plaintext password before storing it.
	PasswordIsHash *bool `json:"password_is_hash,omitempty"`
}

// UID defines model for UID.
type UID = uint32

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Description *Description `json:"description"`
	Disabled    bool         `json:"disabled"`
	Expiration  *time.Time   `json:"expiration"`
	Gid         GID          `json:"gid"`

	// Groupname Group name. Slash (/) is not allowed.
	Groupname Groupname `json:"groupname"`

	// Home Relative path string that must not start with a slash (`/`) and must not contain spaces. Allowed characters: letters, digits, dot (`.`), underscore (`_`), hyphen (`-`), and slash (`/`).
	Home RelativePath `json:"home"`
	Uid  UID          `json:"uid"`

	// Username Username. Slash (/) is not allowed.
	Username Username `json:"username"`
}

// Username Username. Slash (/) is not allowed.
type Username = string

// VerifyHashRequestBody defines model for VerifyHashRequestBody.
type VerifyHashRequestBody struct {
	// Hash Supports: "$1$", "$apr1$", "$5$", "$6$".
	// Optionally raw hex digests (32=MD5, 40=SHA-1, 64=SHA-256, 128=SHA-512).
	// MD5/SHA-1 are supported as legacy and are not recommended.
	Hash string `json:"hash"`

	// Plaintext Plaintext candidate to verify against the stored hash.
	Plaintext *string `json:"plaintext,omitempty"`
}

// VerifyHashResponseBody defines model for VerifyHashResponseBody.
type VerifyHashResponseBody struct {
	// DetectedAlgorithm Detected hash algorithm name (may be "unknown" for non-enum formats).
	DetectedAlgorithm string `json:"detected_algorithm"`

	// Error Optional diagnostic message when verification fails or the format is unsupported.
	Error *string `json:"error"`

	// Verified Whether the plaintext matches the hash.
	Verified bool `json:"verified"`
}

// DirnameParam Directory name. Slash (/) is not allowed.
type DirnameParam = Dirname

// GroupnameParam Group name. Slash (/) is not allowed.
type GroupnameParam = Groupname

// UsernameParam Username. Slash (/) is not allowed.
type UsernameParam = Username

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// AuthzAuthUserFormdataBody defines parameters for AuthzAuthUser.
type AuthzAuthUserFormdataBody struct {
	ClientIp *string `form:"client_ip,omitempty" json:"client_ip,omitempty"`
	Password string  `form:"password" json:"password"`
	Protocol *string `form:"protocol,omitempty" json:"protocol,omitempty"`
	ServerIp *string `form:"server_ip,omitempty" json:"server_ip,omitempty"`
}

// GenerateSecretParams defines parameters for GenerateSecret.
type GenerateSecretParams struct {
	Size *int `form:"size,omitempty" json:"size,omitempty"`
}

// AuthzAuthUserFormdataRequestBody defines body for AuthzAuthUser for application/x-www-form-urlencoded ContentType.
type AuthzAuthUserFormdataRequestBody AuthzAuthUserFormdataBody

// ComputeHashJSONRequestBody defines body for ComputeHash for application/json ContentType.
type ComputeHashJSONRequestBody = ComputeHashRequestBody

// VerifyHashJSONRequestBody defines body for VerifyHash for application/json ContentType.
type VerifyHashJSONRequestBody = VerifyHashRequestBody

// EnsureGroupJSONRequestBody defines body for EnsureGroup for application/json ContentType.
type EnsureGroupJSONRequestBody = EnsureGroupRequestBody

// SetGroupDescriptionJSONRequestBody defines body for SetGroupDescription for application/json ContentType.
type SetGroupDescriptionJSONRequestBody = SetDescriptionRequestBody

// EnsureUserJSONRequestBody defines body for EnsureUser for application/json ContentType.
type EnsureUserJSONRequestBody = EnsureUserRequestBody

// SetUserDescriptionJSONRequestBody defines body for SetUserDescription for application/json ContentType.
type SetUserDescriptionJSONRequestBody = SetDescriptionRequestBody

// SetUserDisabledJSONRequestBody defines body for SetUserDisabled for application/json ContentType.
type SetUserDisabledJSONRequestBody = SetUserDisabledRequestBody

// SetUserExpirationJSONRequestBody defines body for SetUserExpiration for application/json ContentType.
type SetUserExpirationJSONRequestBody = SetUserExpirationRequestBody

// SetUserPasswordJSONRequestBody defines body for SetUserPassword for application/json ContentType.
type SetUserPasswordJSONRequestBody = SetUserPasswordRequestBody
